/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui"],
        display: ["var(--font-display)", "ui-sans-serif", "system-ui"],
        syne: ["var(--font-syne)", "Syne", "ui-sans-serif", "system-ui"],
        dm: ["var(--font-dm)", "DM Sans", "ui-sans-serif", "system-ui"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          border: "hsl(var(--sidebar-border))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        },
        gold: "hsl(var(--gold))",
        drb: {
          turquoise: {
            50: '#E6F9FA',
            100: '#CCF3F5',
            200: '#99E7EB',
            300: '#66DBE1',
            400: '#33CFD7',
            500: '#1CABB0',
            600: '#178991',
            700: '#126771',
            800: '#0C4551',
            900: '#072331',
            950: '#041820',
          },
          lime: {
            50: '#FAFEF0',
            100: '#F5FDE1',
            200: '#EBFBC3',
            300: '#E1F9A5',
            400: '#D7F787',
            500: '#D4F24D',
            600: '#B8D63E',
            700: '#9CBA2F',
            800: '#809E20',
            900: '#648211',
          },
          magenta: {
            500: '#E91E63',
            600: '#D81B60',
            700: '#C2185B',
          },
        },
      },
      backgroundImage: {
        'gradient-premium': 'linear-gradient(135deg, #1CABB0 0%, #D4F24D 100%)',
        'gradient-dark': 'linear-gradient(135deg, #072331 0%, #0C4551 100%)',
        'gradient-turquoise': 'linear-gradient(135deg, #0C4551 0%, #1CABB0 100%)',
        'gradient-blue': 'linear-gradient(135deg, #1CABB0 0%, #178991 100%)',
        'gradient-gold': 'linear-gradient(135deg, #FBBF24 0%, #E8A317 100%)',
        'gradient-emerald': 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
        'gradient-purple': 'linear-gradient(135deg, #8B5CF6 0%, #7C3AED 100%)',
      },
      boxShadow: {
        'premium': '0 10px 40px rgba(28, 171, 176, 0.15)',
        'premium-lg': '0 20px 60px rgba(28, 171, 176, 0.25)',
        'glow': '0 0 30px rgba(212, 242, 77, 0.4)',
        'card': '0 2px 8px rgba(7,35,49,0.08)',
        'card-hover': '0 4px 16px rgba(7,35,49,0.12)',
        'blue-glow': '0 4px 16px rgba(28,171,176,0.3)',
        'turquoise-glow': '0 4px 16px rgba(28,171,176,0.3)',
        'btn': '0 2px 8px rgba(28,171,176,0.20)',
        '100': '0px 1px 3px 0px rgba(16, 24, 40, 0.1), 0px 1px 2px 0px rgba(16, 24, 40, 0.06)',
        '200': '0px 12px 16px -4px rgba(16, 24, 40, 0.1), 0px 4px 20px -2px rgba(16, 24, 40, 0.2)',
        '300': '0px 2px 30px 0px rgba(0, 0, 0, 0.05)',
        '400': '0px 2px 6px 0px rgba(13, 10, 44, 0.08)',
        '500': '0px 12px 16px -4px rgba(16, 24, 40, 0.1)',
      },
      borderRadius: {
        '20': '20px',
      },
      backdropBlur: {
        'xs': '2px',
      },
      animation: {
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-out-right': 'slideOutRight 0.3s ease-in',
        'slide-in-left': 'slideInLeft 0.25s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
        'fade-in-up': 'fadeInUp 0.4s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'float-slower': 'float 12s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 2.5s ease-in-out infinite',
        'shimmer': 'shimmer 3s linear infinite',
        'marquee': 'marquee var(--marquee-duration, 40s) linear infinite',
        'marquee-reverse': 'marqueeReverse var(--marquee-duration, 40s) linear infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'spin-slow': 'spin 20s linear infinite',
        'subtle-zoom': 'subtleZoom 20s ease-in-out infinite alternate',
        'mesh-shift': 'meshShift 12s ease infinite',
        'beam-sweep': 'beamSweep 6s ease-in-out infinite',
        'pulse-ring': 'pulseRing 3s ease-out infinite',
        'float-particle': 'floatParticle 8s ease-in-out infinite',
      },
      keyframes: {
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideOutRight: {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(100%)', opacity: '0' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '33%': { transform: 'translateY(-20px) rotate(3deg)' },
          '66%': { transform: 'translateY(10px) rotate(-2deg)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(28,171,176,0.3), 0 0 60px rgba(28,171,176,0.1)' },
          '50%': { boxShadow: '0 0 30px rgba(28,171,176,0.5), 0 0 100px rgba(28,171,176,0.2)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        marqueeReverse: {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        subtleZoom: {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.05)' },
        },
        meshShift: {
          '0%': { backgroundPosition: '0% 0%' },
          '50%': { backgroundPosition: '100% 100%' },
          '100%': { backgroundPosition: '0% 0%' },
        },
        beamSweep: {
          '0%': { transform: 'translateX(-100%) rotate(-35deg)', opacity: '0' },
          '50%': { opacity: '0.5' },
          '100%': { transform: 'translateX(100%) rotate(-35deg)', opacity: '0' },
        },
        pulseRing: {
          '0%': { transform: 'scale(0.8)', opacity: '0.6' },
          '100%': { transform: 'scale(1.5)', opacity: '0' },
        },
        floatParticle: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-30px) translateX(10px)' },
          '50%': { transform: 'translateY(-15px) translateX(-10px)' },
          '75%': { transform: 'translateY(-25px) translateX(5px)' },
        },
      },
    },
  },
  plugins: [],
};
