/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui"],
        display: ["var(--font-display)", "ui-sans-serif", "system-ui"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          border: "hsl(var(--sidebar-border))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        },
        gold: "hsl(var(--gold))",
        // Travelie palette
        travelie: {
          blue: {
            50: '#EFF6FF',
            100: '#DBEAFE',
            200: '#BFDBFE',
            300: '#93C5FD',
            400: '#60A5FA',
            500: '#4A8FE7',
            600: '#3B7DD8',
            700: '#2E6BC4',
            800: '#1E4D8C',
            900: '#1E3A5F',
          },
          gold: {
            400: '#FBBF24',
            500: '#E8A317',
            600: '#D19A10',
          },
        },
        // Keep backward compat
        drb: {
          turquoise: {
            50: '#E6F9FA',
            100: '#CCF3F5',
            200: '#99E7EB',
            300: '#66DBE1',
            400: '#33CFD7',
            500: '#1CABB0',
            600: '#178991',
            700: '#126771',
            800: '#0C4551',
            900: '#072331',
            950: '#041820',
          },
          lime: {
            50: '#FAFEF0',
            100: '#F5FDE1',
            200: '#EBFBC3',
            300: '#E1F9A5',
            400: '#D7F787',
            500: '#D4F24D',
            600: '#B8D63E',
            700: '#9CBA2F',
            800: '#809E20',
            900: '#648211',
          },
          magenta: {
            500: '#E91E63',
            600: '#D81B60',
            700: '#C2185B',
          },
        },
      },
      backgroundImage: {
        'gradient-premium': 'linear-gradient(135deg, #1CABB0 0%, #D4F24D 100%)',
        'gradient-dark': 'linear-gradient(135deg, #072331 0%, #0C4551 100%)',
        'gradient-turquoise': 'linear-gradient(135deg, #0C4551 0%, #1CABB0 100%)',
        'gradient-blue': 'linear-gradient(135deg, #4A8FE7 0%, #3B7DD8 100%)',
        'gradient-gold': 'linear-gradient(135deg, #FBBF24 0%, #E8A317 100%)',
        'gradient-emerald': 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
        'gradient-purple': 'linear-gradient(135deg, #8B5CF6 0%, #7C3AED 100%)',
      },
      boxShadow: {
        'premium': '0 10px 40px rgba(28, 171, 176, 0.15)',
        'premium-lg': '0 20px 60px rgba(28, 171, 176, 0.25)',
        'glow': '0 0 30px rgba(212, 242, 77, 0.4)',
        'card': '0 1px 3px rgba(0,0,0,0.04), 0 4px 16px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(74,143,231,0.08), 0 8px 24px rgba(0,0,0,0.06)',
        'blue-glow': '0 4px 16px rgba(74,143,231,0.3)',
      },
      backdropBlur: {
        'xs': '2px',
      },
      animation: {
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-out-right': 'slideOutRight 0.3s ease-in',
        'slide-in-left': 'slideInLeft 0.25s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
        'fade-in-up': 'fadeInUp 0.4s ease-out',
      },
      keyframes: {
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideOutRight: {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(100%)', opacity: '0' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
